//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocaWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AkademikEntities : DbContext
    {
        public AkademikEntities()
            : base("name=AkademikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int sp_mehmet_altkategori_ekle(string ad, Nullable<int> kategori_id)
        {
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            var kategori_idParameter = kategori_id.HasValue ?
                new ObjectParameter("kategori_id", kategori_id) :
                new ObjectParameter("kategori_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_altkategori_ekle", adParameter, kategori_idParameter);
        }
    
        public virtual int sp_mehmet_altkategori_Guncelle(Nullable<int> id, string ad, Nullable<int> altkategorimenu_id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            var altkategorimenu_idParameter = altkategorimenu_id.HasValue ?
                new ObjectParameter("altkategorimenu_id", altkategorimenu_id) :
                new ObjectParameter("altkategorimenu_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_altkategori_Guncelle", idParameter, adParameter, altkategorimenu_idParameter);
        }
    
        public virtual int sp_mehmet_altkategori_Sil(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_altkategori_Sil", idParameter);
        }
    
        public virtual ObjectResult<sp_mehmet_altkategoriye_gore_kategori_cek_Result> sp_mehmet_altkategoriye_gore_kategori_cek(string kat_idd)
        {
            var kat_iddParameter = kat_idd != null ?
                new ObjectParameter("kat_idd", kat_idd) :
                new ObjectParameter("kat_idd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mehmet_altkategoriye_gore_kategori_cek_Result>("sp_mehmet_altkategoriye_gore_kategori_cek", kat_iddParameter);
        }
    
        public virtual ObjectResult<sp_mehmet_giris_kontrol_Result> sp_mehmet_giris_kontrol(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mehmet_giris_kontrol_Result>("sp_mehmet_giris_kontrol", userParameter, passParameter);
        }
    
        public virtual int sp_mehmet_Home_Sabit_Guncelle(Nullable<int> id, string t_1, string t_2, string t_3, string t_4, string t_5, string t_6, string t_7, string t_8, string t_9, string gelen)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var t_1Parameter = t_1 != null ?
                new ObjectParameter("t_1", t_1) :
                new ObjectParameter("t_1", typeof(string));
    
            var t_2Parameter = t_2 != null ?
                new ObjectParameter("t_2", t_2) :
                new ObjectParameter("t_2", typeof(string));
    
            var t_3Parameter = t_3 != null ?
                new ObjectParameter("t_3", t_3) :
                new ObjectParameter("t_3", typeof(string));
    
            var t_4Parameter = t_4 != null ?
                new ObjectParameter("t_4", t_4) :
                new ObjectParameter("t_4", typeof(string));
    
            var t_5Parameter = t_5 != null ?
                new ObjectParameter("t_5", t_5) :
                new ObjectParameter("t_5", typeof(string));
    
            var t_6Parameter = t_6 != null ?
                new ObjectParameter("t_6", t_6) :
                new ObjectParameter("t_6", typeof(string));
    
            var t_7Parameter = t_7 != null ?
                new ObjectParameter("t_7", t_7) :
                new ObjectParameter("t_7", typeof(string));
    
            var t_8Parameter = t_8 != null ?
                new ObjectParameter("t_8", t_8) :
                new ObjectParameter("t_8", typeof(string));
    
            var t_9Parameter = t_9 != null ?
                new ObjectParameter("t_9", t_9) :
                new ObjectParameter("t_9", typeof(string));
    
            var gelenParameter = gelen != null ?
                new ObjectParameter("gelen", gelen) :
                new ObjectParameter("gelen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_Home_Sabit_Guncelle", idParameter, t_1Parameter, t_2Parameter, t_3Parameter, t_4Parameter, t_5Parameter, t_6Parameter, t_7Parameter, t_8Parameter, t_9Parameter, gelenParameter);
        }
    
        public virtual ObjectResult<sp_mehmet_homeBig_Image_Result> sp_mehmet_homeBig_Image()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mehmet_homeBig_Image_Result>("sp_mehmet_homeBig_Image");
        }
    
        public virtual int sp_mehmet_HomeImage_Guncelle(Nullable<int> id, string ad, string detay, string urun_url, string resim_ad)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            var detayParameter = detay != null ?
                new ObjectParameter("detay", detay) :
                new ObjectParameter("detay", typeof(string));
    
            var urun_urlParameter = urun_url != null ?
                new ObjectParameter("urun_url", urun_url) :
                new ObjectParameter("urun_url", typeof(string));
    
            var resim_adParameter = resim_ad != null ?
                new ObjectParameter("resim_ad", resim_ad) :
                new ObjectParameter("resim_ad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_HomeImage_Guncelle", idParameter, adParameter, detayParameter, urun_urlParameter, resim_adParameter);
        }
    
        public virtual int sp_mehmet_iletisim_ekle(Nullable<int> id, string fulname, string email, string desc, string subject, Nullable<bool> durum)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fulnameParameter = fulname != null ?
                new ObjectParameter("fulname", fulname) :
                new ObjectParameter("fulname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            var durumParameter = durum.HasValue ?
                new ObjectParameter("durum", durum) :
                new ObjectParameter("durum", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_iletisim_ekle", idParameter, fulnameParameter, emailParameter, descParameter, subjectParameter, durumParameter);
        }
    
        public virtual ObjectResult<sp_mehmet_iletisim_getir_Result> sp_mehmet_iletisim_getir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mehmet_iletisim_getir_Result>("sp_mehmet_iletisim_getir");
        }
    
        public virtual int sp_mehmet_Kategori_ekle(string ad, Nullable<int> kategori_id)
        {
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            var kategori_idParameter = kategori_id.HasValue ?
                new ObjectParameter("kategori_id", kategori_id) :
                new ObjectParameter("kategori_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_Kategori_ekle", adParameter, kategori_idParameter);
        }
    
        public virtual int sp_mehmet_Kategori_Guncelle(Nullable<int> id, string ad, Nullable<int> kat_altkat_id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            var kat_altkat_idParameter = kat_altkat_id.HasValue ?
                new ObjectParameter("kat_altkat_id", kat_altkat_id) :
                new ObjectParameter("kat_altkat_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_Kategori_Guncelle", idParameter, adParameter, kat_altkat_idParameter);
        }
    
        public virtual int sp_mehmet_kategori_Sil(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_kategori_Sil", idParameter);
        }
    
        public virtual ObjectResult<sp_mehmet_kategorileri_cek_Result> sp_mehmet_kategorileri_cek()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mehmet_kategorileri_cek_Result>("sp_mehmet_kategorileri_cek");
        }
    
        public virtual ObjectResult<sp_mehmet_kullanici_bilgi_getir_Result> sp_mehmet_kullanici_bilgi_getir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mehmet_kullanici_bilgi_getir_Result>("sp_mehmet_kullanici_bilgi_getir");
        }
    
        public virtual ObjectResult<sp_mehmet_Menu_Getir_Result> sp_mehmet_Menu_Getir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mehmet_Menu_Getir_Result>("sp_mehmet_Menu_Getir");
        }
    
        public virtual ObjectResult<sp_mehmet_sabitler_Result> sp_mehmet_sabitler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mehmet_sabitler_Result>("sp_mehmet_sabitler");
        }
    
        public virtual int sp_mehmet_urun_Ekle_Guncelle(Nullable<int> id, string ad, string detay, Nullable<int> urun_kategori_id, string resim_ad)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            var detayParameter = detay != null ?
                new ObjectParameter("detay", detay) :
                new ObjectParameter("detay", typeof(string));
    
            var urun_kategori_idParameter = urun_kategori_id.HasValue ?
                new ObjectParameter("urun_kategori_id", urun_kategori_id) :
                new ObjectParameter("urun_kategori_id", typeof(int));
    
            var resim_adParameter = resim_ad != null ?
                new ObjectParameter("resim_ad", resim_ad) :
                new ObjectParameter("resim_ad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_urun_Ekle_Guncelle", idParameter, adParameter, detayParameter, urun_kategori_idParameter, resim_adParameter);
        }
    
        public virtual int sp_mehmet_Urun_Sil(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_Urun_Sil", idParameter);
        }
    
        public virtual ObjectResult<sp_mehmet_urunler_kategoriye_gore_liste_cek_Result> sp_mehmet_urunler_kategoriye_gore_liste_cek(string kattgri)
        {
            var kattgriParameter = kattgri != null ?
                new ObjectParameter("kattgri", kattgri) :
                new ObjectParameter("kattgri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mehmet_urunler_kategoriye_gore_liste_cek_Result>("sp_mehmet_urunler_kategoriye_gore_liste_cek", kattgriParameter);
        }
    
        public virtual int sp_mehmet_user_pasword_update(Nullable<int> id, string user, string password)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mehmet_user_pasword_update", idParameter, userParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_mehmettokak_nested_menu_Result> sp_mehmettokak_nested_menu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mehmettokak_nested_menu_Result>("sp_mehmettokak_nested_menu");
        }
    
        public virtual ObjectResult<sp_mehmettokak_urunliste_cek_Result> sp_mehmettokak_urunliste_cek()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mehmettokak_urunliste_cek_Result>("sp_mehmettokak_urunliste_cek");
        }
    }
}
